name: Sync SamplesByPlatforms to Private Repo

on:
  push:
    branches: [ main, master ]
    paths:
      - 'Src/SamplesByPlatforms/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          path: source

      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          repository: xceedsoftware/xceed-zip-samplesbyplatforms
          token: ${{ secrets.PRIVATE_REPO_PAT }}
          path: target

      - name: Copy files
        run: |
          rm -rf target/*
          cp -r source/Src/SamplesByPlatforms/* target/
          
      - name: Commit and push changes
        run: |
          cd target
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Sync from public repo: ${{ github.event.after }}"
          git push
